spring:
  application:
    name: CodeLaNinjaServer
  profiles:
    active: dev
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: UTC

server:
  port: ${port:8080}
  compression:
    enabled: true

